### ISSUE TITLE
Just FYI

### ISSUE THREAD

**Issue by benmosher** [zertosh/eslint-plugin-dependencies#1]
I maintain a similar plugin at https://github.com/benmosher/eslint-plugin-import.

Seems to do a lot of what you're doing with this. Just wanted to mention it. 😄

**Comment by benmosher** [comment]
Mine doesn't handle `require.resolve` at the moment, but I think it would be trivial to add support for it. Would be a neat addition.

**Comment by geek** [comment]
@benmosher both of these look great.  However, I would rather depend on `eslint-plugin-dependencies`, which has far fewer dependencies and seems more geared toward server side development, or at least development outside of babel.

**Comment by benmosher** [comment]
Fair enough. Mine is much more abort ES6 imports, for sure.

**Comment by zertosh** [comment]
Ah cool, thanks for highlighting it, but I think `eslint-plugin-import` and `eslint-plugin-dependencies` solve very different problems - though there is some overlap with the `no-unresolved` rule.

Seems like `eslint-plugin-import` is mostly for stylistic concerns. While `eslint-plugin-dependencies` is for correctness. Whether they analyse `import`/`require`/`require.resolve` is a minor detail. IMHO, the noteworthy feature differences are: The `no-cyles` rule (to detect cyclic dependencies), the `case-sensitive` rule (to detect incorrect module id casing on Macs), and it uses the parser from your config.

**Comment by benmosher** [comment]
Recent work has been towards style rules, yes. The core rules are still about resolving and parsing remote modules, though. I do have cycle detection, but it is not reported. And my no-unresolved implicitly enforces case.

Anyway, no worries. If you find you want to start supporting Webpack or ES6 import analysis, you may want to take a second look in the future. 😎
