### ISSUE TITLE
Compatibility with NODE_PATH environment variable

### ISSUE THREAD

**Issue by dahjelle** [zertosh/eslint-plugin-dependencies#2]
Hi!

I was just looking for something like this! In my project, however, I'm setting the `NODE_PATH` environment variable to find modules in our project, and it appears that [`node-resolve` doesn't respect `NODE_PATH`](https://github.com/substack/node-resolve/issues/39). However, I was able to get things working by passing the `paths` option to `resolveOpts`, something like:

```
  var resolveOpts = {
    basedir: path.dirname(target),
    extensions: ['.js', '.json', '.node'],
    paths: [path.resolve(process.env.NODE_PATH)],
  };
```

There's one obvious edge case here—if `NODE_PATH` isn't set—and I suspect there may be more.

Is this something you'd consider adding to your plugin?

**Comment by zertosh** [comment]
Sure, I'd take a PR that takes an option to set `paths`.
